### ISSUE TITLE
Plan 1.2 release

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1250]

**Comment by Daniel-KM** [comment]
Currently, all the features of Omeka Classic are managed by Omeka S (and many more in fact).
Only two remain:

- [ ] Choice of a site as root without "/s/my-site" (#870, #331, https://forum.omeka.org/t/root-url-as-site-1/6204/11, etc.)
- [ ] Html data type (#1241) 

So if the 1.2 release has these two features, all the current installations of Omeka Classic will be upgradable lossless.

I add a third point for ergonomic reasons: 

- [ ] Common place for config options (#1282)

**Comment by jimsafley** [comment]
[Scripto](https://github.com/omeka-s-modules/Scripto) cannot be released until 1.2 is released. No real rush, just stoking the fire.

**Comment by zerocrates** [comment]
@mebrett Manual updates need to be done before this

**Comment by zerocrates** [comment]
Targeting July 31

**Comment by zerocrates** [comment]
@Daniel-KM:

1.2 is probably/definitely not going to contain any of those 3 items.

The "front page/site" issue is definitely high on our list of priorities and will likely be addressed in 1.3.

The HTML type I'm not sure if we'll want to do in the core itself, but we'd certainly be open to making improvements or changes to the data type system if needed for that to work as a module, including the kinds of things you've talked about in terms of adding a sort of "base" type to the value table.

I'm not as sure about what you're envisioning for your final item about the configuration, though.
