### ISSUE TITLE
Resource templates improvements

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1565]
The resource templates, formerly called input grids in old software, are a main feature of Omeka S, but some points are missing and cannot be added simply by a module. So this is a list of things to work on.

- [x] Multiple data type by property (for example multiple value suggest for subjects and a literal for free subjects; or a creator from different databases). Technically in the Omeka scheme, it can be done with one property with multiple datatypes or multiple properties with one datatype (#1597).
- [x] A specific label for each of the specific datatypes (for example a label Dewey for a normalized subject and a label "Theme" for a value from a custom vocab) (#1597).
- [x] Automatic filling and deletion of the opposite property for value resources (for example when editing item Alpha and adding the property "is part of" to item Beta, set the property "has part" in the item Beta to the item Alpha). Ideally automatically via the the semantic ontology (inverse), else manually via an option in the template (module [Reciprocal](https://github.com/Daniel-KM/Omeka-S-module-Reciprocal)).
- [x] A default value (#1610).
- [x] A non-modifiable automatic value, for example for an identifier, with a specific format (for example a shelf number "mylib-user2-001", or from a helper for more complex formats, like for ark) (#1612, the format of the identifier is managed outside).
- [x] Allow to create a new resource when editing another one for a smoother workflow with linked resources (#1608).
- [ ] Limit the value resources to select to a specific list (with a default query) (postponed).
- [x] Autocompletion with existing values when the user fills a value in a property (#1611).
- [x] Limit the language to some specific ones (more related to ux) (#1610).
- [ ] Qualifying a value (for example the creator can be an author or a director or a producer, or a date can be "uncertain" or "certain", or a place can be a river or a village). This qualification avoids to multiply properties for the same concept, in particular for large libraries. Ideally, it should be done automatically in a semantic way: many properties of various ontologies are related to Dublin Core properties. But it may be done simpler with a merge of multiple properties in forms, display and search. The ux may be similar than the language field, that set a characteristic to the value too; may be a limited list from custom vocab, or a free field.

For these features, it is simpler to upgrade the core, in particular the table resource_template, but the code in many other places too (at least forms, but potentially display, search, api output). 

All changes are in development for August, except the last one.

These features are built for the future [digital library Manioc](http://www.manioc.org) of Université des Antilles and Université de la Guyane, currently managed with [Greenstone](http://www.greenstone.org).

**Comment by zerocrates** [comment]
I think some of these make obvious sense as enhancements: in particular options around default values, languages, etc.

Multiple data types by property I think works at least in a few ways (one of just letting users basically configure the "add a value" selector to have multiple choices in particular seems like a workable change). The follow-on of having values for the same property have different labels depending on their datatype... I'm a little more skeptical on that one, and how that would work.

**Comment by Daniel-KM** [comment]
I implemented 1 and 2 so that current users won't see change.

**Comment by Daniel-KM** [comment]
![image](https://user-images.githubusercontent.com/2138485/88070484-06900200-cb73-11ea-8e4c-96f7b42df9c9.png)

See pr for more info.

**Comment by Daniel-KM** [comment]
The third point (fill the reciprocal value of the linked resource) is implemented in a new separate module [Reciprocal](https://github.com/Daniel-KM/Omeka-S-module-Reciprocal).
It's probably useless to add a setting for each property of each template for that, so it is independent of other issues.

**Comment by Daniel-KM** [comment]
The feature to allow to create a new resource when editing another one for a smoother workflow with linked resources (#1608) is related to the resource form improvements too, but not to the templates.

**Comment by Daniel-KM** [comment]
For the language in resource form (#1610):

## The resource template: 

![image](https://user-images.githubusercontent.com/2138485/91349994-5d2dd300-e7e6-11ea-877e-50087c488548.png)

## The resource form:

![image](https://user-images.githubusercontent.com/2138485/91350261-b85fc580-e7e6-11ea-8932-d9e56d438419.png)

**Comment by Daniel-KM** [comment]
## Selection of default data types: 

![image](https://user-images.githubusercontent.com/2138485/91413169-04dcec80-e84b-11ea-8abc-4f2496dad882.png)

### Creating a new item during edition of an item:

![image](https://user-images.githubusercontent.com/2138485/91413450-6bfaa100-e84b-11ea-85b9-66824e598840.png)

**Comment by Daniel-KM** [comment]
### Autocompletion (configurable by template and by template property):

![Screenshot_20200828_102359](https://user-images.githubusercontent.com/2138485/91540561-43da7300-e91b-11ea-855e-12f27d7d1662.png)

**Comment by Daniel-KM** [comment]
Pull requests for the settings has been refactorized in different pull requests: #1617, #1619, #1620, #1621, #1622, #1623 and #1624. 

To try this feature directly, you can use the module [Advanced Resource Template](https://gitlab.com/Daniel-KM/Omeka-S-module-AdvancedResourceTemplate) that uses the prs and that adds the features above.

**Comment by Daniel-KM** [comment]
All points of this request, except the last one (qualified values), are now available in Omeka 3 and the module [Advanced Resource Template](https://gitlab.com/Daniel-KM/Omeka-S-module-AdvancedResourceTemplate). 

Technically, the module uses simply all the code proposed here.
